### ISSUE TITLE
No static method getFont

### ISSUE THREAD

**Issue by mrmosi13** [pranavpandey/dynamic-toasts#2]
Hello Dear 
i want to use this library in my project . 
add in to dependencies and sync successfully . and use this command in my project like this :
DynamicToast.makeError(getApplicationContext(), "Error Message", Toast.LENGTH_SHORT).show();

and after run project , i faced "unfortunately app has stopped" . after that i read logs and see this error :

FATAL EXCEPTION: main Process: com.example.mohammad_pc.crm_android,PID:29510java.lang.NoSuchMethodError: **No static method getFont**(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.example.mohammad_pc.crm_android-1/base.apk)
                                                       
what is this ? guide me please 
thank you

**Comment by pranavpandey** [comment]
This library does not uses getFont() method. This issue generally occurs due to the conflict between support libraries. 

Try to update your support libraries to 27.0.2 which is used by this library or you can exclude the transitive support library dependency from Dynamic Toasts using Gradle.
https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991

**Comment by pranavpandey** [comment]
Closing this issue for now. Kindly comment if issue persists.
